package arcade.store.gui;


/*
 * MainShopGUI.java
 *
 * Created on December 7, 2010, 12:17 PM
 */

public class MainPageViewBeta
{

	/**
	 *
	 * @author  Drew Sternesky, Yijia Mu, Marcus Molchany
	 */
	public static class MainShopGUI extends javax.swing.JFrame {

		/** Creates new form MainShopGUI */
		public MainShopGUI() {
			initComponents();
		}

		/** This method is called from within the constructor to
		 * initialize the form.
		 * WARNING: Do NOT modify this code. The content of this method is
		 * always regenerated by the Form Editor.
		 */
		// <editor-fold defaultstate="collapsed" desc="Generated Code">
		private void initComponents() {

			jTabbedPane1 = new javax.swing.JTabbedPane();
			jScrollPane2 = new javax.swing.JScrollPane();
			jPanel10 = new javax.swing.JPanel();
			jTabbedPane6 = new javax.swing.JTabbedPane();
			jScrollPane14 = new javax.swing.JScrollPane();
			jPanel21 = new javax.swing.JPanel();
			jPanel22 = new javax.swing.JPanel();
			jTextField10 = new javax.swing.JTextField();
			jTextField11 = new javax.swing.JTextField();
			jTextField12 = new javax.swing.JTextField();
			jLabel16 = new javax.swing.JLabel();
			jButton20 = new javax.swing.JButton();
			jButton21 = new javax.swing.JButton();
			jLabel17 = new javax.swing.JLabel();
			jLabel18 = new javax.swing.JLabel();
			jLabel19 = new javax.swing.JLabel();
			jScrollPane9 = new javax.swing.JScrollPane();
			jList3 = new javax.swing.JList();
			jScrollPane8 = new javax.swing.JScrollPane();
			jPanel11 = new javax.swing.JPanel();
			jPanel12 = new javax.swing.JPanel();
			jLabel10 = new javax.swing.JLabel();
			jScrollPane10 = new javax.swing.JScrollPane();
			jTable2 = new javax.swing.JTable();
			jPanel13 = new javax.swing.JPanel();
			jLabel7 = new javax.swing.JLabel();
			jLabel8 = new javax.swing.JLabel();
			jLabel9 = new javax.swing.JLabel();
			jTextField4 = new javax.swing.JTextField();
			jTextField5 = new javax.swing.JTextField();
			jTextField3 = new javax.swing.JTextField();
			jPanel14 = new javax.swing.JPanel();
			jButton12 = new javax.swing.JButton();
			jButton13 = new javax.swing.JButton();
			jButton22 = new javax.swing.JButton();
			jTabbedPane3 = new javax.swing.JTabbedPane();
			jScrollPane11 = new javax.swing.JScrollPane();
			jPanel17 = new javax.swing.JPanel();
			jPanel18 = new javax.swing.JPanel();
			jPanel23 = new javax.swing.JPanel();
			jLabel20 = new javax.swing.JLabel();
			jScrollPane19 = new javax.swing.JScrollPane();
			jList4 = new javax.swing.JList();
			jScrollPane20 = new javax.swing.JScrollPane();
			jScrollPane12 = new javax.swing.JScrollPane();
			jPanel24 = new javax.swing.JPanel();
			jPanel25 = new javax.swing.JPanel();
			jLabel21 = new javax.swing.JLabel();
			jScrollPane21 = new javax.swing.JScrollPane();
			jList5 = new javax.swing.JList();
			jScrollPane22 = new javax.swing.JScrollPane();
			jScrollPane15 = new javax.swing.JScrollPane();
			jPanel26 = new javax.swing.JPanel();
			jPanel27 = new javax.swing.JPanel();
			jLabel22 = new javax.swing.JLabel();
			jScrollPane23 = new javax.swing.JScrollPane();
			jList6 = new javax.swing.JList();
			jScrollPane24 = new javax.swing.JScrollPane();
			jTabbedPane2 = new javax.swing.JTabbedPane();
			jScrollPane1 = new javax.swing.JScrollPane();
			jPanel1 = new javax.swing.JPanel();
			jPanel2 = new javax.swing.JPanel();
			jScrollPane4 = new javax.swing.JScrollPane();
			jList1 = new javax.swing.JList();
			jLabel1 = new javax.swing.JLabel();
			jPanel3 = new javax.swing.JPanel();
			jComboBox2 = new javax.swing.JComboBox();
			jComboBox4 = new javax.swing.JComboBox();
			jScrollPane5 = new javax.swing.JScrollPane();
			jPanel4 = new javax.swing.JPanel();
			jPanel5 = new javax.swing.JPanel();
			jButton1 = new javax.swing.JButton();
			jButton2 = new javax.swing.JButton();
			jButton3 = new javax.swing.JButton();
			jButton4 = new javax.swing.JButton();
			jButton5 = new javax.swing.JButton();
			jButton6 = new javax.swing.JButton();
			jLabel2 = new javax.swing.JLabel();
			jLabel3 = new javax.swing.JLabel();
			jScrollPane13 = new javax.swing.JScrollPane();
			jPanel15 = new javax.swing.JPanel();
			jPanel16 = new javax.swing.JPanel();
			jLabel11 = new javax.swing.JLabel();
			jButton14 = new javax.swing.JButton();
			jButton15 = new javax.swing.JButton();
			jButton16 = new javax.swing.JButton();
			jButton17 = new javax.swing.JButton();
			jTextField6 = new javax.swing.JTextField();
			jTextField7 = new javax.swing.JTextField();
			jTextField8 = new javax.swing.JTextField();
			jTextField9 = new javax.swing.JTextField();
			jButton18 = new javax.swing.JButton();
			jButton19 = new javax.swing.JButton();
			jScrollPane16 = new javax.swing.JScrollPane();
			jPanel19 = new javax.swing.JPanel();
			jPanel20 = new javax.swing.JPanel();
			jScrollPane17 = new javax.swing.JScrollPane();
			jTable3 = new javax.swing.JTable();
			jLabel12 = new javax.swing.JLabel();
			jLabel13 = new javax.swing.JLabel();
			jComboBox5 = new javax.swing.JComboBox();
			jLabel14 = new javax.swing.JLabel();
			jComboBox6 = new javax.swing.JComboBox();
			jLabel15 = new javax.swing.JLabel();
			jScrollPane18 = new javax.swing.JScrollPane();
			jList2 = new javax.swing.JList();
			jScrollPane3 = new javax.swing.JScrollPane();
			jPanel6 = new javax.swing.JPanel();
			jButton8 = new javax.swing.JButton();
			jButton9 = new javax.swing.JButton();
			jButton10 = new javax.swing.JButton();
			jTextField1 = new javax.swing.JTextField();
			jButton11 = new javax.swing.JButton();
			jScrollPane6 = new javax.swing.JScrollPane();
			jPanel7 = new javax.swing.JPanel();
			jButton7 = new javax.swing.JButton();
			jTextField2 = new javax.swing.JTextField();
			jPanel8 = new javax.swing.JPanel();
			jLabel4 = new javax.swing.JLabel();
			jComboBox1 = new javax.swing.JComboBox();
			jLabel5 = new javax.swing.JLabel();
			jComboBox3 = new javax.swing.JComboBox();
			jPanel9 = new javax.swing.JPanel();
			jScrollPane7 = new javax.swing.JScrollPane();
			jTable1 = new javax.swing.JTable();
			jLabel6 = new javax.swing.JLabel();

			setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

			jTextField10.setText("jTextField10");

			jTextField11.setText("jTextField11");

			jTextField12.setText("jTextField12");

			jLabel16.setText("Available Creddits:");

			jButton20.setText("Buy Item(s)");

			jButton21.setText("Drop Item(s)");

			jLabel17.setText("My Check Out:");

			jLabel18.setText("Items Cost:");

			jLabel19.setText("Remaining Creddits:");

			jList3.setModel(new javax.swing.AbstractListModel() {
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
				public int getSize() { return strings.length; }
				public Object getElementAt(int i) { return strings[i]; }
			});
			jScrollPane9.setViewportView(jList3);

			javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
			jPanel22.setLayout(jPanel22Layout);
			jPanel22Layout.setHorizontalGroup(
					jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel22Layout.createSequentialGroup()
							.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel22Layout.createSequentialGroup()
											.addContainerGap()
											.addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
													.addGap(18, 18, 18)
													.addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
															.addGroup(jPanel22Layout.createSequentialGroup()
																	.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																			.addGroup(jPanel22Layout.createSequentialGroup()
																					.addGap(35, 35, 35)
																					.addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
																					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
																							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																							.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																									.addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
																									.addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
																									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																									.addGap(69, 69, 69))
																									.addGroup(jPanel22Layout.createSequentialGroup()
																											.addGap(57, 57, 57)
																											.addComponent(jButton20)
																											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																											.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																													.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																															.addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
																															.addComponent(jTextField11)
																															.addComponent(jTextField12))
																															.addGroup(jPanel22Layout.createSequentialGroup()
																																	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																	.addComponent(jButton21)))))
																																	.addContainerGap())
			);
			jPanel22Layout.setVerticalGroup(
					jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel22Layout.createSequentialGroup()
							.addGap(8, 8, 8)
							.addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel22Layout.createSequentialGroup()
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
													.addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
													.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
													.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
															.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
															.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																	.addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																	.addGap(49, 49, 49)
																	.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																			.addComponent(jButton20)
																			.addComponent(jButton21)))
																			.addGroup(jPanel22Layout.createSequentialGroup()
																					.addGap(16, 16, 16)
																					.addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
																					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);

			javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
			jPanel21.setLayout(jPanel21Layout);
			jPanel21Layout.setHorizontalGroup(
					jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel21Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(95, Short.MAX_VALUE))
			);
			jPanel21Layout.setVerticalGroup(
					jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel21Layout.createSequentialGroup()
							.addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(156, Short.MAX_VALUE))
			);

			jScrollPane14.setViewportView(jPanel21);

			jTabbedPane6.addTab("My Checkout Page", jScrollPane14);

			jLabel10.setText("My Purchased Games:");

			jTable2.setModel(new javax.swing.table.DefaultTableModel(
					new Object [][] {
							{null, null, null, null},
							{null, null, null, null},
							{null, null, null, null},
							{null, null, null, null}
					},
					new String [] {
							"Title 1", "Title 2", "Title 3", "Title 4"
					}
			));
			jScrollPane10.setViewportView(jTable2);

			javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
			jPanel12.setLayout(jPanel12Layout);
			jPanel12Layout.setHorizontalGroup(
					jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel12Layout.createSequentialGroup()
							.addGap(171, 171, 171)
							.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(199, Short.MAX_VALUE))
							.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
									.addContainerGap()
									.addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addContainerGap())
			);
			jPanel12Layout.setVerticalGroup(
					jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel12Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
							.addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);

			jLabel7.setText("Manage My Account");

			jLabel8.setText("Total Gameplay: ");

			jLabel9.setText("Availabe Creddits: ");

			jTextField4.setText("jTextField4");
			jTextField4.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jTextField4ActionPerformed(evt);
				}
			});

			jTextField5.setText("jTextField5");

			jTextField3.setText("(Username)");

			javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
			jPanel14.setLayout(jPanel14Layout);
			jPanel14Layout.setHorizontalGroup(
					jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGap(0, 99, Short.MAX_VALUE)
			);
			jPanel14Layout.setVerticalGroup(
					jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGap(0, 92, Short.MAX_VALUE)
			);

			jButton12.setText("Purchase Credits ");

			jButton13.setText("Edit My Profile");

			jButton22.setText("Edit My History");

			javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
			jPanel13.setLayout(jPanel13Layout);
			jPanel13Layout.setHorizontalGroup(
					jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel13Layout.createSequentialGroup()
							.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel13Layout.createSequentialGroup()
											.addContainerGap()
											.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(jPanel13Layout.createSequentialGroup()
													.addGap(27, 27, 27)
													.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
															.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
															.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
															.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																	.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
																	.addGap(37, 37, 37)
																	.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																			.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																					.addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																					.addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																					.addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																					.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																							.addGroup(jPanel13Layout.createSequentialGroup()
																									.addGap(37, 37, 37)
																									.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
																									.addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
																									.addGap(32, 32, 32))
			);
			jPanel13Layout.setVerticalGroup(
					jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel13Layout.createSequentialGroup()
							.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel13Layout.createSequentialGroup()
											.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
											.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(jPanel13Layout.createSequentialGroup()
													.addGap(16, 16, 16)
													.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
															.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
															.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																	.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
																	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																	.addComponent(jButton12)
																	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																	.addComponent(jButton13)
																	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																	.addComponent(jButton22)))
																	.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);

			javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
			jPanel11.setLayout(jPanel11Layout);
			jPanel11Layout.setHorizontalGroup(
					jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel11Layout.createSequentialGroup()
							.addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel11Layout.createSequentialGroup()
											.addGap(17, 17, 17)
											.addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(jPanel11Layout.createSequentialGroup()
													.addContainerGap()
													.addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
													.addContainerGap(14, Short.MAX_VALUE))
			);
			jPanel11Layout.setVerticalGroup(
					jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel11Layout.createSequentialGroup()
							.addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(18, 18, 18)
							.addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(87, Short.MAX_VALUE))
			);

			jScrollPane8.setViewportView(jPanel11);

			jTabbedPane6.addTab("My Shop Profile", jScrollPane8);

			javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
			jPanel10.setLayout(jPanel10Layout);
			jPanel10Layout.setHorizontalGroup(
					jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel10Layout.createSequentialGroup()
							.addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(146, Short.MAX_VALUE))
			);
			jPanel10Layout.setVerticalGroup(
					jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel10Layout.createSequentialGroup()
							.addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(150, Short.MAX_VALUE))
			);

			jScrollPane2.setViewportView(jPanel10);

			jTabbedPane1.addTab("My Account", jScrollPane2);

			jTabbedPane3.setPreferredSize(new java.awt.Dimension(300, 100));

			jLabel20.setText("Categories:");

			jList4.setModel(new javax.swing.AbstractListModel() {
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
				public int getSize() { return strings.length; }
				public Object getElementAt(int i) { return strings[i]; }
			});
			jScrollPane19.setViewportView(jList4);

			javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
			jPanel23.setLayout(jPanel23Layout);
			jPanel23Layout.setHorizontalGroup(
					jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel23Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jLabel20))
									.addContainerGap(21, Short.MAX_VALUE))
			);
			jPanel23Layout.setVerticalGroup(
					jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel23Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel20)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
							.addContainerGap())
			);

			javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
			jPanel18.setLayout(jPanel18Layout);
			jPanel18Layout.setHorizontalGroup(
					jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel18Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(18, 18, 18)
							.addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(207, Short.MAX_VALUE))
			);
			jPanel18Layout.setVerticalGroup(
					jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel18Layout.createSequentialGroup()
							.addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel18Layout.createSequentialGroup()
											.addContainerGap()
											.addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(jPanel18Layout.createSequentialGroup()
													.addGap(45, 45, 45)
													.addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
													.addContainerGap(184, Short.MAX_VALUE))
			);

			javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
			jPanel17.setLayout(jPanel17Layout);
			jPanel17Layout.setHorizontalGroup(
					jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			);
			jPanel17Layout.setVerticalGroup(
					jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			);

			jScrollPane11.setViewportView(jPanel17);

			jTabbedPane3.addTab("Apparels", jScrollPane11);

			jLabel21.setText("Categories:");

			jList5.setModel(new javax.swing.AbstractListModel() {
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
				public int getSize() { return strings.length; }
				public Object getElementAt(int i) { return strings[i]; }
			});
			jScrollPane21.setViewportView(jList5);

			javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
			jPanel25.setLayout(jPanel25Layout);
			jPanel25Layout.setHorizontalGroup(
					jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel25Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jLabel21))
									.addContainerGap(21, Short.MAX_VALUE))
			);
			jPanel25Layout.setVerticalGroup(
					jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel25Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel21)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
							.addContainerGap())
			);

			javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
			jPanel24.setLayout(jPanel24Layout);
			jPanel24Layout.setHorizontalGroup(
					jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel24Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(18, 18, 18)
							.addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(207, Short.MAX_VALUE))
			);
			jPanel24Layout.setVerticalGroup(
					jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel24Layout.createSequentialGroup()
							.addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel24Layout.createSequentialGroup()
											.addContainerGap()
											.addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(jPanel24Layout.createSequentialGroup()
													.addGap(45, 45, 45)
													.addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
													.addContainerGap(184, Short.MAX_VALUE))
			);

			jScrollPane12.setViewportView(jPanel24);

			jTabbedPane3.addTab("Comics & Books", jScrollPane12);

			jLabel22.setText("Categories:");

			jList6.setModel(new javax.swing.AbstractListModel() {
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
				public int getSize() { return strings.length; }
				public Object getElementAt(int i) { return strings[i]; }
			});
			jScrollPane23.setViewportView(jList6);

			javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
			jPanel27.setLayout(jPanel27Layout);
			jPanel27Layout.setHorizontalGroup(
					jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel27Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jLabel22))
									.addContainerGap(21, Short.MAX_VALUE))
			);
			jPanel27Layout.setVerticalGroup(
					jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel27Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel22)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
							.addContainerGap())
			);

			javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
			jPanel26.setLayout(jPanel26Layout);
			jPanel26Layout.setHorizontalGroup(
					jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel26Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(18, 18, 18)
							.addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(207, Short.MAX_VALUE))
			);
			jPanel26Layout.setVerticalGroup(
					jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel26Layout.createSequentialGroup()
							.addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel26Layout.createSequentialGroup()
											.addContainerGap()
											.addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(jPanel26Layout.createSequentialGroup()
													.addGap(45, 45, 45)
													.addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
													.addContainerGap(184, Short.MAX_VALUE))
			);

			jScrollPane15.setViewportView(jPanel26);

			jTabbedPane3.addTab("Special Items", jScrollPane15);

			jTabbedPane1.addTab("Gamer's Collectibles", jTabbedPane3);

			jList1.setModel(new javax.swing.AbstractListModel() {
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
				public int getSize() { return strings.length; }
				public Object getElementAt(int i) { return strings[i]; }
			});
			jScrollPane4.setViewportView(jList1);

			jLabel1.setText("Game Genre: ");

			javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
			jPanel2.setLayout(jPanel2Layout);
			jPanel2Layout.setHorizontalGroup(
					jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
									.addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
									.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
									.addContainerGap())
			);
			jPanel2Layout.setVerticalGroup(
					jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel2Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(11, 11, 11)
							.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
							.addContainerGap())
			);

			jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

			jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
			jComboBox4.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jComboBox4ActionPerformed(evt);
				}
			});

			jButton1.setText("jButton1");

			jButton2.setText("jButton1");

			jButton3.setText("jButton1");

			jButton4.setText("jButton1");

			jButton5.setText("jButton1");

			jButton6.setText("jButton1");

			javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
			jPanel5.setLayout(jPanel5Layout);
			jPanel5Layout.setHorizontalGroup(
					jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel5Layout.createSequentialGroup()
							.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel5Layout.createSequentialGroup()
											.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(jPanel5Layout.createSequentialGroup()
													.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
													.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
													.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
													.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
															.addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
															.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
			);
			jPanel5Layout.setVerticalGroup(
					jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel5Layout.createSequentialGroup()
							.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
									.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
									.addGap(18, 18, 18)
									.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
											.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
			);

			javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
			jPanel4.setLayout(jPanel4Layout);
			jPanel4Layout.setHorizontalGroup(
					jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel4Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(212, Short.MAX_VALUE))
			);
			jPanel4Layout.setVerticalGroup(
					jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel4Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(203, Short.MAX_VALUE))
			);

			jScrollPane5.setViewportView(jPanel4);

			jLabel2.setText("Search By: ");

			jLabel3.setText("Filter By: ");

			javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
			jPanel3.setLayout(jPanel3Layout);
			jPanel3Layout.setHorizontalGroup(
					jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel3Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addGroup(jPanel3Layout.createSequentialGroup()
											.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
											.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addGap(47, 47, 47)
											.addComponent(jLabel3)
											.addGap(27, 27, 27)
											.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
											.addContainerGap())
			);
			jPanel3Layout.setVerticalGroup(
					jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel3Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
									.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jLabel3)
									.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
									.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);

			javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
			jPanel1.setLayout(jPanel1Layout);
			jPanel1Layout.setHorizontalGroup(
					jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(157, Short.MAX_VALUE))
			);
			jPanel1Layout.setVerticalGroup(
					jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel1Layout.createSequentialGroup()
											.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addContainerGap())
											.addGroup(jPanel1Layout.createSequentialGroup()
													.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
													.addGap(344, 344, 344))))
			);

			jScrollPane1.setViewportView(jPanel1);

			jTabbedPane2.addTab("What's Hot", jScrollPane1);

			jLabel11.setText("Today's Special Offer:");

			jButton14.setText("jButton14");

			jButton15.setText("jButton15");

			jButton16.setText("jButton16");

			jButton17.setText("jButton17");

			jTextField6.setText("jTextField6");

			jTextField7.setText("jTextField7");

			jTextField8.setText("jTextField8");

			jTextField9.setText("jTextField9");

			jButton18.setText("Ad 1");

			jButton19.setText("Ad 2");

			javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
			jPanel16.setLayout(jPanel16Layout);
			jPanel16Layout.setHorizontalGroup(
					jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel16Layout.createSequentialGroup()
							.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel16Layout.createSequentialGroup()
											.addContainerGap()
											.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
													.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addGroup(jPanel16Layout.createSequentialGroup()
															.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																	.addGroup(jPanel16Layout.createSequentialGroup()
																			.addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
																			.addGap(18, 18, 18))
																			.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
																					.addGap(10, 10, 10)
																					.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
																					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																					.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																							.addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
																							.addGroup(jPanel16Layout.createSequentialGroup()
																									.addGap(10, 10, 10)
																									.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
																									.addGap(18, 18, 18)
																									.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																											.addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
																											.addGroup(jPanel16Layout.createSequentialGroup()
																													.addGap(10, 10, 10)
																													.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
																													.addGap(10, 10, 10)
																													.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																															.addGroup(jPanel16Layout.createSequentialGroup()
																																	.addGap(10, 10, 10)
																																	.addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
																																	.addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
																																	.addGroup(jPanel16Layout.createSequentialGroup()
																																			.addGap(49, 49, 49)
																																			.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																																					.addComponent(jButton19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																																					.addComponent(jButton18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))))
																																					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);
			jPanel16Layout.setVerticalGroup(
					jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel16Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
									.addComponent(jButton17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(jButton16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(jButton15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
									.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
									.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
											.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGap(32, 32, 32)
											.addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addGap(18, 18, 18)
											.addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addContainerGap(198, Short.MAX_VALUE))
			);

			javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
			jPanel15.setLayout(jPanel15Layout);
			jPanel15Layout.setHorizontalGroup(
					jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel15Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
							.addContainerGap(19, Short.MAX_VALUE))
			);
			jPanel15Layout.setVerticalGroup(
					jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			);

			jScrollPane13.setViewportView(jPanel15);

			jTabbedPane2.addTab("Daily Specials", jScrollPane13);

			jTable3.setModel(new javax.swing.table.DefaultTableModel(
					new Object [][] {
							{null, null, null, null},
							{null, null, null, null},
							{null, null, null, null},
							{null, null, null, null}
					},
					new String [] {
							"Title 1", "Title 2", "Title 3", "Title 4"
					}
			));
			jScrollPane17.setViewportView(jTable3);

			jLabel12.setText("The Rental / Trade Center: ");

			jLabel13.setText("Search By: ");

			jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

			jLabel14.setText("Filter By:");

			jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
			jComboBox6.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jComboBox6ActionPerformed(evt);
				}
			});

			jLabel15.setText("Genre:");

			jList2.setModel(new javax.swing.AbstractListModel() {
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
				public int getSize() { return strings.length; }
				public Object getElementAt(int i) { return strings[i]; }
			});
			jScrollPane18.setViewportView(jList2);

			javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
			jPanel20.setLayout(jPanel20Layout);
			jPanel20Layout.setHorizontalGroup(
					jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel20Layout.createSequentialGroup()
							.addGap(9, 9, 9)
							.addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(jLabel12)
									.addGroup(jPanel20Layout.createSequentialGroup()
											.addGap(10, 10, 10)
											.addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
													.addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
													.addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
															.addGroup(jPanel20Layout.createSequentialGroup()
																	.addGap(19, 19, 19)
																	.addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																	.addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addGap(42, 42, 42)
																	.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																	.addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																	.addGroup(jPanel20Layout.createSequentialGroup()
																			.addGap(18, 18, 18)
																			.addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
																			.addContainerGap(31, Short.MAX_VALUE))
			);
			jPanel20Layout.setVerticalGroup(
					jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel20Layout.createSequentialGroup()
							.addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel20Layout.createSequentialGroup()
											.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
											.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
													.addContainerGap(36, Short.MAX_VALUE)
													.addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
															.addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
															.addComponent(jLabel14))
															.addGap(18, 18, 18)
															.addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
															.addContainerGap())
			);

			javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
			jPanel19.setLayout(jPanel19Layout);
			jPanel19Layout.setHorizontalGroup(
					jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel19Layout.createSequentialGroup()
							.addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGap(143, 143, 143))
			);
			jPanel19Layout.setVerticalGroup(
					jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
							.addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGap(79, 79, 79))
			);

			jScrollPane16.setViewportView(jPanel19);

			jTabbedPane2.addTab("Rentals / Trades", jScrollPane16);

			jButton8.setText("jButton8");
			jButton8.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jButton8ActionPerformed(evt);
				}
			});

			jButton9.setText("jButton8");

			jButton10.setText("jButton8");

			jTextField1.setText("jTextField1");
			jTextField1.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jTextField1ActionPerformed(evt);
				}
			});

			jButton11.setText("jButton11");

			javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
			jPanel6.setLayout(jPanel6Layout);
			jPanel6Layout.setHorizontalGroup(
					jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel6Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
									.addGroup(jPanel6Layout.createSequentialGroup()
											.addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
											.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addGap(28, 28, 28)
											.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGap(32, 32, 32)
											.addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addContainerGap(122, Short.MAX_VALUE))
			);
			jPanel6Layout.setVerticalGroup(
					jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel6Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel6Layout.createSequentialGroup()
											.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
													.addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
													.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
													.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addContainerGap(215, Short.MAX_VALUE))
													.addGroup(jPanel6Layout.createSequentialGroup()
															.addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
															.addGap(215, 215, 215))))
			);

			jScrollPane3.setViewportView(jPanel6);

			jTabbedPane2.addTab("Review Of the Week", jScrollPane3);

			jButton7.setText("Search");

			jTextField2.setText("jTextField2");

			jLabel4.setText("Search By: ");

			jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
			jComboBox1.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jComboBox1ActionPerformed(evt);
				}
			});

			jLabel5.setText("Filter By: ");

			jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
			jComboBox3.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jComboBox3ActionPerformed(evt);
				}
			});

			jTable1.setModel(new javax.swing.table.DefaultTableModel(
					new Object [][] {
							{null, null, null, null},
							{null, null, null, null},
							{null, null, null, null},
							{null, null, null, null}
					},
					new String [] {
							"Title 1", "Title 2", "Title 3", "Title 4"
					}
			));
			jScrollPane7.setViewportView(jTable1);

			javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
			jPanel9.setLayout(jPanel9Layout);
			jPanel9Layout.setHorizontalGroup(
					jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel9Layout.createSequentialGroup()
							.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
			);
			jPanel9Layout.setVerticalGroup(
					jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
			);

			javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
			jPanel8.setLayout(jPanel8Layout);
			jPanel8Layout.setHorizontalGroup(
					jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel8Layout.createSequentialGroup()
							.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel8Layout.createSequentialGroup()
											.addGap(23, 23, 23)
											.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addGap(93, 93, 93)
											.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addGap(18, 18, 18)
											.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(jPanel8Layout.createSequentialGroup()
													.addGap(10, 10, 10)
													.addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
													.addContainerGap())
			);
			jPanel8Layout.setVerticalGroup(
					jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel8Layout.createSequentialGroup()
							.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
									.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(jLabel5))
									.addGap(18, 18, 18)
									.addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addContainerGap())
			);

			jLabel6.setText("The Complete Game Store Catalogue:");

			javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
			jPanel7.setLayout(jPanel7Layout);
			jPanel7Layout.setHorizontalGroup(
					jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel7Layout.createSequentialGroup()
							.addGap(40, 40, 40)
							.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
											.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
											.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
											.addComponent(jButton7))
											.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
											.addContainerGap())
			);
			jPanel7Layout.setVerticalGroup(
					jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(jPanel7Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
											.addComponent(jButton7)
											.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
											.addContainerGap())
			);

			jScrollPane6.setViewportView(jPanel7);

			jTabbedPane2.addTab("Store Catalogue", jScrollPane6);

			jTabbedPane1.addTab("Game Shop", jTabbedPane2);

			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(
					layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
							.addGap(104, 104, 104)
							.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
							.addContainerGap())
			);
			layout.setVerticalGroup(
					layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
			);

			pack();
		}// </editor-fold>

		private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
			// TODO add your handling code here:
		}

		private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {
			// TODO add your handling code here:
		}

		private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
			// TODO add your handling code here:
		}

		private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
			// TODO add your handling code here:
		}

		private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
			// TODO add your handling code here:
		}

		private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {
			// TODO add your handling code here:
		}

		private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {
			// TODO add your handling code here:
		}

		/**
		 * @param args the command line arguments
		 */
		public static void main(String args[]) {
			java.awt.EventQueue.invokeLater(new Runnable() {
				public void run() {
					new MainShopGUI().setVisible(true);
				}
			});
		}

		// Variables declaration - do not modify
		private javax.swing.JButton jButton1;
		private javax.swing.JButton jButton10;
		private javax.swing.JButton jButton11;
		private javax.swing.JButton jButton12;
		private javax.swing.JButton jButton13;
		private javax.swing.JButton jButton14;
		private javax.swing.JButton jButton15;
		private javax.swing.JButton jButton16;
		private javax.swing.JButton jButton17;
		private javax.swing.JButton jButton18;
		private javax.swing.JButton jButton19;
		private javax.swing.JButton jButton2;
		private javax.swing.JButton jButton20;
		private javax.swing.JButton jButton21;
		private javax.swing.JButton jButton22;
		private javax.swing.JButton jButton3;
		private javax.swing.JButton jButton4;
		private javax.swing.JButton jButton5;
		private javax.swing.JButton jButton6;
		private javax.swing.JButton jButton7;
		private javax.swing.JButton jButton8;
		private javax.swing.JButton jButton9;
		private javax.swing.JComboBox jComboBox1;
		private javax.swing.JComboBox jComboBox2;
		private javax.swing.JComboBox jComboBox3;
		private javax.swing.JComboBox jComboBox4;
		private javax.swing.JComboBox jComboBox5;
		private javax.swing.JComboBox jComboBox6;
		private javax.swing.JLabel jLabel1;
		private javax.swing.JLabel jLabel10;
		private javax.swing.JLabel jLabel11;
		private javax.swing.JLabel jLabel12;
		private javax.swing.JLabel jLabel13;
		private javax.swing.JLabel jLabel14;
		private javax.swing.JLabel jLabel15;
		private javax.swing.JLabel jLabel16;
		private javax.swing.JLabel jLabel17;
		private javax.swing.JLabel jLabel18;
		private javax.swing.JLabel jLabel19;
		private javax.swing.JLabel jLabel2;
		private javax.swing.JLabel jLabel20;
		private javax.swing.JLabel jLabel21;
		private javax.swing.JLabel jLabel22;
		private javax.swing.JLabel jLabel3;
		private javax.swing.JLabel jLabel4;
		private javax.swing.JLabel jLabel5;
		private javax.swing.JLabel jLabel6;
		private javax.swing.JLabel jLabel7;
		private javax.swing.JLabel jLabel8;
		private javax.swing.JLabel jLabel9;
		private javax.swing.JList jList1;
		private javax.swing.JList jList2;
		private javax.swing.JList jList3;
		private javax.swing.JList jList4;
		private javax.swing.JList jList5;
		private javax.swing.JList jList6;
		private javax.swing.JPanel jPanel1;
		private javax.swing.JPanel jPanel10;
		private javax.swing.JPanel jPanel11;
		private javax.swing.JPanel jPanel12;
		private javax.swing.JPanel jPanel13;
		private javax.swing.JPanel jPanel14;
		private javax.swing.JPanel jPanel15;
		private javax.swing.JPanel jPanel16;
		private javax.swing.JPanel jPanel17;
		private javax.swing.JPanel jPanel18;
		private javax.swing.JPanel jPanel19;
		private javax.swing.JPanel jPanel2;
		private javax.swing.JPanel jPanel20;
		private javax.swing.JPanel jPanel21;
		private javax.swing.JPanel jPanel22;
		private javax.swing.JPanel jPanel23;
		private javax.swing.JPanel jPanel24;
		private javax.swing.JPanel jPanel25;
		private javax.swing.JPanel jPanel26;
		private javax.swing.JPanel jPanel27;
		private javax.swing.JPanel jPanel3;
		private javax.swing.JPanel jPanel4;
		private javax.swing.JPanel jPanel5;
		private javax.swing.JPanel jPanel6;
		private javax.swing.JPanel jPanel7;
		private javax.swing.JPanel jPanel8;
		private javax.swing.JPanel jPanel9;
		private javax.swing.JScrollPane jScrollPane1;
		private javax.swing.JScrollPane jScrollPane10;
		private javax.swing.JScrollPane jScrollPane11;
		private javax.swing.JScrollPane jScrollPane12;
		private javax.swing.JScrollPane jScrollPane13;
		private javax.swing.JScrollPane jScrollPane14;
		private javax.swing.JScrollPane jScrollPane15;
		private javax.swing.JScrollPane jScrollPane16;
		private javax.swing.JScrollPane jScrollPane17;
		private javax.swing.JScrollPane jScrollPane18;
		private javax.swing.JScrollPane jScrollPane19;
		private javax.swing.JScrollPane jScrollPane2;
		private javax.swing.JScrollPane jScrollPane20;
		private javax.swing.JScrollPane jScrollPane21;
		private javax.swing.JScrollPane jScrollPane22;
		private javax.swing.JScrollPane jScrollPane23;
		private javax.swing.JScrollPane jScrollPane24;
		private javax.swing.JScrollPane jScrollPane3;
		private javax.swing.JScrollPane jScrollPane4;
		private javax.swing.JScrollPane jScrollPane5;
		private javax.swing.JScrollPane jScrollPane6;
		private javax.swing.JScrollPane jScrollPane7;
		private javax.swing.JScrollPane jScrollPane8;
		private javax.swing.JScrollPane jScrollPane9;
		private javax.swing.JTabbedPane jTabbedPane1;
		private javax.swing.JTabbedPane jTabbedPane2;
		private javax.swing.JTabbedPane jTabbedPane3;
		private javax.swing.JTabbedPane jTabbedPane6;
		private javax.swing.JTable jTable1;
		private javax.swing.JTable jTable2;
		private javax.swing.JTable jTable3;
		private javax.swing.JTextField jTextField1;
		private javax.swing.JTextField jTextField10;
		private javax.swing.JTextField jTextField11;
		private javax.swing.JTextField jTextField12;
		private javax.swing.JTextField jTextField2;
		private javax.swing.JTextField jTextField3;
		private javax.swing.JTextField jTextField4;
		private javax.swing.JTextField jTextField5;
		private javax.swing.JTextField jTextField6;
		private javax.swing.JTextField jTextField7;
		private javax.swing.JTextField jTextField8;
		private javax.swing.JTextField jTextField9;
		// End of variables declaration

	}
}
